baseURL = 'prism-kumamoto-u/prism-kumamoto-u.gihub.io'
languageCode = 'ja'
title = "Prism"
theme = "ananke"

# 生のHTMLをmdファイルに書くために追加
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true